name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: 7.4
            laravel: 6.*
          - php: 7.4
            laravel: 7.*
          - php: 8.0
            laravel: 8.*
          - php: 8.0
            laravel: 9.*
          - php: 8.1
            laravel: 10.*
          - php: 8.2
            laravel: 11.*
          - php: 8.3
            laravel: 11.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, dom, fileinfo, mysql, sqlite, pgsql
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create Laravel test application
      run: |
        composer create-project laravel/laravel test-app ${{ matrix.laravel }} --prefer-dist --no-interaction
        cd test-app
        composer require herkod/laravel-tr:dev-main --no-interaction

    - name: Run tests
      run: |
        cd test-app
        ./vendor/bin/phpunit --configuration ../phpunit.xml

    - name: Upload coverage to Codecov
      if: matrix.php == '8.3' && matrix.laravel == '11.*'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
